version: "3.7"
services:
  database:
    container_name: symfony-api-database
    image: postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  pgadmin:
    container_name: symfony-api-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./docker/pgadmin.json:/pgadmin4/servers.json
    ports:
      - "5400:80"
    links:
      - database
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: symfony-api
    environment:
      SYMFONY_PROJECT_NAME: sympfony-app
      DATABASE_URL: pgsql://symfony@database:5432/symfony
      APP_ENV: dev
      APP_SECRET: e92948d0-ddaf-4164-ae32-6daef7cf0388
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - database
